[package]
name = "rubet"
version = "0.1.0"
authors = ["kydas <kadasilva22@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_core = "0.44.0"
rusoto_sqs = "0.44.0"
consul = "*"